{
 "title": "Bank Movements",
 "description": "Bank account information",
 "tags": [ "bank" ],
 "time": { "from": "now-5y", "to": "now" },
 "panels": [
  { "title": "General info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last balance",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT balance\nFROM movements\nWHERE date in (select max(date) from movements)\nLIMIT 1; \n"
    }
   ]
  },
  {
   "title": "Number of movements",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\nFROM movements\n"
    }
   ]
  },
  {
   "title": "Last imported month",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT DATE_FORMAT(date, '%Y-%m') as month\nFROM movements\nWHERE date in (select max(date) from movements)\nLIMIT 1; \n"
    }
   ]
  },
  {
   "title": "Last pays",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT amount,  date AS time\nFROM movements\nWHERE concept LIKE '%NOMINA%'\nORDER BY date DESC\n"
    }
   ]
  },
  { "title": "Balance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Overall Balance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  balance\nFROM movements\nWHERE\n  $__timeFilter(date)\nORDER BY date"
    }
   ]
  },
  {
   "title": "Balance at pay moment",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  balance\nFROM movements\nWHERE\n  $__timeFilter(date) AND concept LIKE '%NOMINA%'\nORDER BY date"
    }
   ]
  },
  { "title": "Spending & Incoming", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Spending & Incoming by month",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_SUB(date, INTERVAL DAYOFMONTH(date) - 1 DAY) AS time,\n  SUM(amount) as incoming\nFROM movements\nWHERE\n  $__timeFilter(date) AND amount > 0\nGROUP BY YEAR(date), MONTH(date)\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  DATE_SUB(date, INTERVAL DAYOFMONTH(date) - 1 DAY) AS time,\n  SUM(amount) as spending\nFROM movements\nWHERE\n  $__timeFilter(date) AND amount < 0\nGROUP BY YEAR(date), MONTH(date)\nORDER BY date"
    }
   ]
  },
  {
   "title": "Diff by month",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT incoming.date AS time,\n       incoming.amount + spending.amount AS diff\nFROM   (SELECT SUM(amount) AS amount,\n               date\n        FROM   movements\n        WHERE  amount > 0\n        GROUP  BY YEAR(date),\n                  MONTH(date)) AS incoming\n       JOIN (SELECT SUM(amount) AS amount,\n                    date\n             FROM   movements\n             WHERE  amount < 0\n             GROUP  BY YEAR(date),\n                       MONTH(date)) AS spending\n         ON DATE_FORMAT(spending.date, '%Y-%m') =\n            DATE_FORMAT(incoming.date, '%Y-%m')  "
    }
   ]
  },
  { "title": "Spending", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Spending by concept",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(amount) as spending,\n  concept\nFROM movements\nWHERE\n  amount < 0\nGROUP BY concept\nORDER BY spending\n\n"
    }
   ]
  },
  {
   "title": "Spending by subconcept",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(amount) as spending,\n  subconcept\nFROM movements\nWHERE\n  amount < 0\nGROUP BY subconcept\nORDER BY spending\n"
    }
   ]
  },
  {
   "title": "Biggest spendings",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_FORMAT(date, '%Y-%m-%d') as date,\n  amount,\n  concept,\n  subconcept\nFROM movements\nWHERE\n  amount < 0\nORDER BY amount\n\n"
    }
   ]
  }
 ]
}